version: '3.8'

services:
  plantsmtldb:
    container_name: catalog_postgres_db
    image: postgres:12.3-alpine
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdatadscatalog:/var/lib/postgresql/data
    networks:
      - dscatalog_network

  pgadminplants:
    container_name: catalog_pgadmin4
    image: dpage/pgadmin4:4.23
    restart: always
    depends_on:
      - plantsmtldb
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    networks:
      - dscatalog_network

volumes:
  dbdatadscatalog:
networks:
  dscatalog_network:
    driver: bridge
